# Harry Potter Dataset
## Data Wrangling: Joining & Combining Data

<img src='hogwarts.JPG'>
<i>Image by inspiredbythemuse from <a href="https://pixabay.com/illustrations/hogwarts-owl-hedwig-harry-potter-2036645/">Pixabay</a></i>

Now we will look more into joining and combining data. It is often the case where you are working with data from various sources and need to combine this data for further analysis.

In this notebook, you will use a number of Harry Potter related datasets to practice data manipulation. First, download the notebook and the Excel file titled `harry_potter.xlsx` and place them in the same folder. 

Also note that there are sometimes different ways to do the same thing when using Python and Pandas for data manipulation. Some ways are more efficient than others, especially with larger data sets, but since these datasets are so small, the suggested solutions may not be the most efficient. Instead, our goal is to show you different options when it comes to completing the tasks.

The complete set of Harry Potter datasets can be found here: [Kaggle](https://www.kaggle.com/gulsahdemiryurek/harry-potter-dataset)

### Initial Imports

In [1]:
# import common Libraries
import pandas as pd
import numpy as np

In [2]:
 # import data from Excel 
fileName = "harry_potter.xlsx" #ensure file is in same location as notebook or add path

# create ExcelFile object
xls = pd.ExcelFile(fileName)

# load individual sheets / we'll explain the data as we go along
gryffindor = pd.read_excel(xls, 'gryffindor', index_col='ID')
slytherin = pd.read_excel(xls, 'slytherin', index_col='ID')
hufflepuff = pd.read_excel(xls, 'hufflepuff', index_col='ID')
ravenclaw = pd.read_excel(xls, 'ravenclaw', index_col='ID')
other1 = pd.read_excel(xls, 'other1', index_col='ID')
other2 = pd.read_excel(xls, 'other2', index_col='ID')
loyalty = pd.read_excel(xls, 'loyalty', index_col='ID')
dead_characters = pd.read_excel(xls, 'dead_characters', index_col='ID')
gryffindor_bloodstatus = pd.read_excel(xls, 'gryffindor_bloodstatus', index_col='ID')
gryffindor_species = pd.read_excel(xls, 'gryffindor_species', index_col='ID')
color = pd.read_excel(xls, 'color', index_col='ID')
wand = pd.read_excel(xls, 'wand', index_col='ID')

Let's take a look at the first dataset: `gryffindor`

In [3]:
gryffindor.head()

Name  Gender         Job       House  \
ID                                                                            
0                        Harry James Potter    Male     Student  Gryffindor   
1                     Ronald Bilius Weasley    Male     Student  Gryffindor   
2                     Hermione Jean Granger  Female     Student  Gryffindor   
3   Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                        Neville Longbottom    Male     Student  Gryffindor   

                Patronus Species Blood status  
ID                                             
0                   Stag   Human   Half-blood  
1   Jack Russell terrier   Human   Pure-blood  
2                  Otter   Human  Muggle-born  
3                Phoenix   Human   Half-blood  
4          Non-corporeal   Human   Pure-blood

Let's also take a closer look at the `Species` attribute.

In [4]:
gryffindor['Species'].value_counts()

Human                      36
Human                       3
Werewolf                    1
Human (Werewolf traits)     1
Ghost                       1
Name: Species, dtype: int64

Notice that there are two values labeled `Human`. Why is that?

This happens a lot when loading messy datasets (especially with Excel files) where there can be either leading or trailing spaces. There are a couple of ways to clean this up, and one of the easiest ways is to use the `strip()` method.

#### Student Practice
Try to perform the following tasks on the indicated dataset. Then check your answers as I walk through the solutions. 

**Exercise:** Use the `strip()` method to remove leading or trailing spaces from the `Species` attribute. Print the value counts for the `Species` column to double check your work.

In [5]:
gryffindor['Species'] = gryffindor['Species'].str.strip()

In [6]:
gryffindor['Species'].value_counts()

Human                      39
Werewolf                    1
Human (Werewolf traits)     1
Ghost                       1
Name: Species, dtype: int64

Good. That took care of the trailing spaces for this column. We can now create a function to remove leading and trailing spaces from all columns of their respective DataFrames. 

**Bonus Exercise:** Create a function called `whitespace` that takes as input a list of the Harry Potter DataFrames. This function should strip the leading and trailing spaces from each column that has an `object` data type for each DataFrame.

In [7]:
slytherin['Species'].value_counts()

Human     25
Human      2
Ghost      1
Name: Species, dtype: int64

In [8]:
df_list = [slytherin, loyalty]

def whitespace(df_list):
    for df in df_list:
        for col in df.columns:
            if df[col].dtype == 'object':
                df[col] = df[col].str.strip()

In [9]:
whitespace(df_list)

In [10]:
slytherin['Species'].value_counts()

Human    27
Ghost     1
Name: Species, dtype: int64

### Adding Rows

#### Append
Let's now look at the [append()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.append.html) method. The `append()` method appends rows from the other dataframe to the end of the caller, returning a new object.

Note the following from the `Python Data Science Handbook`:

> Keep in mind that unlike the `append()` and `extend()` methods of Python lists, the `append()` method in Pandas does not modify the original object–instead it creates a new object with the combined data. It also is not a very efficient method, because it involves creation of a new index and data buffer. Thus, if you plan to do multiple append operations, it is generally better to build a list of DataFrames and pass them all at once to the `concat()` function.

In [11]:
# create a simple dataset
df1 = pd.DataFrame({'a': [1,2,3,4],
                  'b': [5,6,7,8]})

df1

a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [12]:
# create another simple dataset
df2 = pd.DataFrame({'a': [9,10,11,12],
                  'b': [13,14,15,16]})
df2

a   b
0   9  13
1  10  14
2  11  15
3  12  16

In [13]:
# use append() to add rows of df2 to the bottom of df1, notice the duplicate indices
df3 = df1.append(df2)
df3

<ipython-input-13-a5a8bc19ce74>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df1.append(df2)


a   b
0   1   5
1   2   6
2   3   7
3   4   8
0   9  13
1  10  14
2  11  15
3  12  16

In [14]:
# setup alternate DataFrame
df2_alternate = pd.DataFrame({'a': [9,10,11,12],
                  'c': [13,14,15,16]})
df2_alternate

a   c
0   9  13
1  10  14
2  11  15
3  12  16

In [15]:
# column in df2_alternate that is not in df1 is added as new column
df3_alternate = df1.append(df2_alternate)
df3_alternate

<ipython-input-15-e7c042c693b1>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3_alternate = df1.append(df2_alternate)


a    b     c
0   1  5.0   NaN
1   2  6.0   NaN
2   3  7.0   NaN
3   4  8.0   NaN
0   9  NaN  13.0
1  10  NaN  14.0
2  11  NaN  15.0
3  12  NaN  16.0

In [16]:
# argument `verify_integrity` warns about duplicate indices
# df3_alternate = df1.append(df2_alternate, verify_integrity=True)
# df3_alternate

In [17]:
# using `ignore_index`
df3_alternate = df1.append(df2_alternate, ignore_index=True)
df3_alternate

<ipython-input-17-8ddf82f1d863>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3_alternate = df1.append(df2_alternate, ignore_index=True)


a    b     c
0   1  5.0   NaN
1   2  6.0   NaN
2   3  7.0   NaN
3   4  8.0   NaN
4   9  NaN  13.0
5  10  NaN  14.0
6  11  NaN  15.0
7  12  NaN  16.0

#### Concat

Panda's [concat()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) method can be used for simple concatenation of arrays and dataframes along a particular axis. One important thing to note is that Pandas concatenation preserves indices, even if the result will have duplicate indices (similar to the append method above). We'll see this more in a moment.

In [18]:
# remind ourselves of the DataFrame
df1

a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [19]:
# remind ourselves of the DataFrame
df2

a   b
0   9  13
1  10  14
2  11  15
3  12  16

In [20]:
# using concat
pd.concat([df1,df2])

a   b
0   1   5
1   2   6
2   3   7
3   4   8
0   9  13
1  10  14
2  11  15
3  12  16

In [21]:
# using axis=1
pd.concat([df1,df2], axis=1)

a  b   a   b
0  1  5   9  13
1  2  6  10  14
2  3  7  11  15
3  4  8  12  16

In [22]:
# can pass keys for multi-index
pd.concat([df1,df2], axis=1, keys=['key1', 'key2'])

key1    key2    
     a  b    a   b
0    1  5    9  13
1    2  6   10  14
2    3  7   11  15
3    4  8   12  16

What is the difference between `concat` and `append`? `Concat` gives the flexibility to join based on the axis( all rows or all columns). `Append` is the specific case (axis=0, join='outer') of `concat`

Let's review basic outer vs inner joins.

In [23]:
# create another DataFrame 
df4 = pd.DataFrame({'a': [17,18,19,20],
                  'c': [21,22,23,24]})
df4

a   c
0  17  21
1  18  22
2  19  23
3  20  24

In [24]:
# outer join (df1 union df4)
pd.concat([df1,df4], join='outer')

a    b     c
0   1  5.0   NaN
1   2  6.0   NaN
2   3  7.0   NaN
3   4  8.0   NaN
0  17  NaN  21.0
1  18  NaN  22.0
2  19  NaN  23.0
3  20  NaN  24.0

In [25]:
# inner join (df1 intersect df4)
pd.concat([df1,df4], join='inner')

a
0   1
1   2
2   3
3   4
0  17
1  18
2  19
3  20

You should also notice that the index (in this case) column didn't change with the new DataFrame. This is good in some cases since some indices are unique identifiers. But in some circumstances, you don't want the index to remain the same (for example when you have multiple rows with the same index). In these cases, you could use the `ignore_index=True` argument to reset the indices.

In [26]:
# using default concat method
pd.concat([df1,df2])

a   b
0   1   5
1   2   6
2   3   7
3   4   8
0   9  13
1  10  14
2  11  15
3  12  16

In [27]:
# using ignore_index=True
pd.concat([df1,df2], ignore_index=True)

a   b
0   1   5
1   2   6
2   3   7
3   4   8
4   9  13
5  10  14
6  11  15
7  12  16

#### Student Practice
Try to perform the following tasks on the indicated dataset. Then check your answers as I walk through the solutions. 

We now want to create a new DataFrame that contains all the characters from the Harry Potter series. 

*Note: There are easier ways to do this all at once, but we want to call your attention to some things so we will add to this DataFrame a little at a time.*

**Exercise:** Use the `copy()` method to copy the `gryffindor` dataset to a new DataFrame that you will call `hp_characters`.

In [28]:
hp_characters = gryffindor.copy()
hp_characters

Name  Gender  \
ID                                                     
0                         Harry James Potter    Male   
1                      Ronald Bilius Weasley    Male   
2                      Hermione Jean Granger  Female   
3    Albus Percival Wulfric Brian Dumbledore    Male   
4                         Neville Longbottom    Male   
5                               Fred Weasley    Male   
6                             George Weasley    Male   
7              Ginevra (Ginny) Molly Weasley  Female   
8                                Dean Thomas    Male   
9                            Seamus Finnigan    Male   
10                            Lily J. Potter  Female   
11                              James Potter    Male   
141                          Tywin Lannister    Male   
142                         Cersei Lannister  Female   
143                          Jaime Lannister    Male   
144                         Tyrion Lannister    Male   
145                        Joffrey Baratheon    Male   
12                              Sirius Black    Male   
13                          Remus John Lupin    Male   
14                           Peter Pettigrew    Male   
15                    Percy Ignatius Weasley    Male   
16             (Bill) William Arthur Weasley    Male   
17                           Charles Weasley    Male   
18                               Lee Jordan     Male   
19                               Oliver Wood    Male   
20                          Angelina Johnson  Female   
21                                Katie Bell  Female   
22                            Alicia Spinnet  Female   
23                            Lavender Brown  Female   
24                             Parvati Patil  Female   
25                              Romilda Vane  Female   
26                             Colin Creevey    Male   
27                           Cormac McLaggen    Male   
28                        Minerva McGonagall  Female   
29                             Molly Weasley  Female   
30                            Arthur Weasley    Male   
67                         Godric Gryffindor    Male   
69              Nicholas de Mimsy-Porpington    Male   
96                          Frank Longbottom    Male   
122                           Dennis Creevey    Male   
126                      James Sirius Potter    Male   
127                     Rose Granger-Weasley  Female   

                                                   Job       House  \
ID                                                                   
0                                              Student  Gryffindor   
1                                              Student  Gryffindor   
2                                              Student  Gryffindor   
3                                           Headmaster  Gryffindor   
4                                              Student  Gryffindor   
5                                              Student  Gryffindor   
6                                              Student  Gryffindor   
7                                              Student  Gryffindor   
8                                              Student  Gryffindor   
9                                              Student  Gryffindor   
10                                                 NaN  Gryffindor   
11                                                 NaN  Gryffindor   
141                          Game of Thrones Character  Gryffindor   
142                          Game of Thrones Character  Gryffindor   
143                          Game of Thrones Character  Gryffindor   
144                          Game of Thrones Character  Gryffindor   
145                          Game of Thrones Character  Gryffindor   
12                                                 NaN  Gryffindor   
13         Professor of Defence Against the Dark Arts   Gryffindor   
14                       The Servant of Lord Voldemort  Gryffindor   
15   Student|Prefect|  Personal ass

**Exercise:** Add the `slytherin` dataset to the new `hp_characters` DataFrame using the `append()` method.

In [29]:
hp_characters.append(slytherin)

<ipython-input-29-6bc40d7c7d5d>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  hp_characters.append(slytherin)


Name  Gender  \
ID                                                     
0                         Harry James Potter    Male   
1                      Ronald Bilius Weasley    Male   
2                      Hermione Jean Granger  Female   
3    Albus Percival Wulfric Brian Dumbledore    Male   
4                         Neville Longbottom    Male   
..                                       ...     ...   
89                         Augustus Rookwood    Male   
90                           Antonin Dolohov    Male   
91                             Corban Yaxley    Male   
123                     Albus Severus Potter    Male   
124                 Scorpius Hyperion Malfoy    Male   

                                                   Job       House  \
ID                                                                   
0                                              Student  Gryffindor   
1                                              Student  Gryffindor   
2                                              Student  Gryffindor   
3                                           Headmaster  Gryffindor   
4                                              Student  Gryffindor   
..                                                 ...         ...   
89                                         Unspeakable   Slytherin   
90                                         Death Eater   Slytherin   
91   Head of the Department of Magical Law Enforcement   Slytherin   
123                                            Student   Slytherin   
124                                            Student   Slytherin   

                 Patronus Species              Blood status  
ID                                                           
0                    Stag   Human                Half-blood  
1    Jack Russell terrier   Human                Pure-blood  
2                   Otter   Human               Muggle-born  
3                 Phoenix   Human                Half-blood  
4           Non-corporeal   Human                Pure-blood  
..                    ...     ...                       ...  
89                   None   Human  Pure-blood or half-blood  
90                   None   Human  Pure-blood or Half-blood  
91                   None   Human  Pure-blood or Half-blood  
123                     ?   Human                Half-blood  
124                     ?   Human                Pure-blood  

[70 rows x 7 columns]

**Exercise**: Add the `ravenclaw` data to `hp_characters` using the `concat` method.

In [30]:
hp_characters = pd.concat([hp_characters, ravenclaw ])
hp_characters

Name  Gender  \
ID                                                      
0                          Harry James Potter    Male   
1                       Ronald Bilius Weasley    Male   
2                       Hermione Jean Granger  Female   
3     Albus Percival Wulfric Brian Dumbledore    Male   
4                          Neville Longbottom    Male   
5                                Fred Weasley    Male   
6                              George Weasley    Male   
7               Ginevra (Ginny) Molly Weasley  Female   
8                                 Dean Thomas    Male   
9                             Seamus Finnigan    Male   
10                             Lily J. Potter  Female   
11                               James Potter    Male   
141                           Tywin Lannister    Male   
142                          Cersei Lannister  Female   
143                           Jaime Lannister    Male   
144                          Tyrion Lannister    Male   
145                         Joffrey Baratheon    Male   
12                               Sirius Black    Male   
13                           Remus John Lupin    Male   
14                            Peter Pettigrew    Male   
15                     Percy Ignatius Weasley    Male   
16              (Bill) William Arthur Weasley    Male   
17                            Charles Weasley    Male   
18                                Lee Jordan     Male   
19                                Oliver Wood    Male   
20                           Angelina Johnson  Female   
21                                 Katie Bell  Female   
22                             Alicia Spinnet  Female   
23                             Lavender Brown  Female   
24                              Parvati Patil  Female   
25                               Romilda Vane  Female   
26                              Colin Creevey    Male   
27                            Cormac McLaggen    Male   
28                         Minerva McGonagall  Female   
29                              Molly Weasley  Female   
30                             Arthur Weasley    Male   
67                          Godric Gryffindor    Male   
69               Nicholas de Mimsy-Porpington    Male   
96                           Frank Longbottom    Male   
122                            Dennis Creevey    Male   
126                       James Sirius Potter    Male   
127                      Rose Granger-Weasley  Female   
31                          Quirinus Quirrell    Male   
32                                  Cho Chang  Female   
33                              Luna Lovegood  Female   
34                          Gilderoy Lockhart    Male   
35                            Filius Flitwick    Male   
36                  Sybill Patricia Trelawney  Female   
37                         Garrick Ollivander    Male   
38   Myrtle Elizabeth Warren (Moaning Myrtle)  Female   
39                                Padma Patil  Female   
40                             Michael Corner    Male   
41                         Marietta Edgecombe  Female   
42                                 Terry Boot    Male   
43                          Anthony Goldstein    Male   
63                        Penelope Clearwater  Female   
64                               Roger Davies    Male   
65                               Marcus Belby    Male   
68                           Rowena Ravenclaw  Female   
78                           Helena Ravenclaw  Female   

                                                   Job       House  \
ID                                                                   
0                                              Student  Gryffindor   
1                                              Student  Gryffindor   
2                                              Student  Gryffindor   
3                                           Headmaster  Gryffindor   
4                                              Student  Gryffindor   
5               

Let's now take a look at the last Hogwarts house, Hufflepuff.

In [31]:
# view hufflepuff data
hufflepuff

Name  Gender  \
ID                                    
76         Helga Hufflepuff  Female   
77                Fat Friar    Male   
79         Nymphadora Tonks  Female   
80            Pomona Sprout  Female   
81         Newton Scamander    Male   
139          Dr. Greg Longo    Male   
140       Dr. Mike Morabito    Male   
82           Cedric Diggory    Male   
83   Justin Finch-Fletchley    Male   
84          Zacharias Smith    Male   
85            Hannah Abbott  Female   
86         Ernest Macmillan    Male   
87              Susan Bones  Female   
112             Edgar Bones    Male   
125      Edward Remus Lupin    Male   

                                                   Job       House  \
ID                                                                   
76                               Founder of Hufflepuff  Hufflepuff   
77                              Hufflepuff House Ghost  Hufflepuff   
79                                               Auror  Hufflepuff   
80   Professor of Herbology | Head of Hufflepuff House  Hufflepuff   
81   Employee in the Beast Division of the Departme...  Hufflepuff   
139                                          Professor  Hufflepuff   
140                                          Professor  Hufflepuff   
82                                             Student  Hufflepuff   
83                                             Student  Hufflepuff   
84                                             Student  Hufflepuff   
85                                             Student  Hufflepuff   
86                                             Student  Hufflepuff   
87                                             Student  Hufflepuff   
112                                                NaN  Hufflepuff   
125                                            Student  Hufflepuff   

              Patronus                 Species              Blood status  \
ID                                                                         
76                   ?                   Human  Pure-blood or half-blood   
77                   ?                   Ghost                       NaN   
79   Jack rabbit, Wolf                   Human                Half-blood   
80       Non-corporeal                   Human  Pure-blood or half-blood   
81                   ?                   Human  Pure-blood or half-blood   
139              Eagle                   Human               Muggle-born   
140              Eagle                   Human               Muggle-born   
82                   ?                   Human                Pure-blood   
83       Non-corporeal                   Human               Muggle-born   
84                   ?                   Human  Pure-blood or half-blood   
85       Non-corporeal                   Human                Half-blood   
86                Boar                   Human                Pure-blood   
87                   ?                   Human                Half-blood   
112                  ?                   Human  Pure-blood or half-blood   
125                  ?  Human (Metamorphmagus)                Half-blood   

                                                Skills  
ID                                                      
76   Food-related Charms. Many traditional Hogwarts...  
77                          Curing peasants of the pox  
79                      Talented Auror, Metamorphmagus  
80                                           Herbology  
81          Magizoology, Order of Merlin, Second Class  
139           Can charm others using Muggle statistics  
140                   Builds robots to fight Voldemort  
82                                      Skilled Seeker  
83                                                 NaN  
84                                              Chaser  
85    Defensive spells, learned with Dumbledore's Army  
86   Revising, being a Prefect, getting the wrong e...  
87    Defensive spells, learned with Dumbledore's Army  
112                 

Notice that this DataFrame has an extra attribute, `Skills`. Also, if you look at `ID` 139 and 140, there appears to be some bad data in the file. We'll clean that up in a moment. Let's see what happens when we add this data to the new DataFrame.

**Exercise:** Add `hufflepuff` to the `hp_characters` DataFrame. What happens with the `Skill` column?

In [32]:
hp_characters = pd.concat([hp_characters, hufflepuff ])
hp_characters

Name  Gender         Job       House  \
ID                                                                             
0                         Harry James Potter    Male     Student  Gryffindor   
1                      Ronald Bilius Weasley    Male     Student  Gryffindor   
2                      Hermione Jean Granger  Female     Student  Gryffindor   
3    Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                         Neville Longbottom    Male     Student  Gryffindor   
..                                       ...     ...         ...         ...   
85                             Hannah Abbott  Female     Student  Hufflepuff   
86                          Ernest Macmillan    Male     Student  Hufflepuff   
87                               Susan Bones  Female     Student  Hufflepuff   
112                              Edgar Bones    Male         NaN  Hufflepuff   
125                       Edward Remus Lupin    Male     Student  Hufflepuff   

                 Patronus                 Species              Blood status  \
ID                                                                            
0                    Stag                   Human                Half-blood   
1    Jack Russell terrier                   Human                Pure-blood   
2                   Otter                   Human               Muggle-born   
3                 Phoenix                   Human                Half-blood   
4           Non-corporeal                   Human                Pure-blood   
..                    ...                     ...                       ...   
85          Non-corporeal                   Human                Half-blood   
86                   Boar                   Human                Pure-blood   
87                      ?                   Human                Half-blood   
112                     ?                   Human  Pure-blood or half-blood   
125                     ?  Human (Metamorphmagus)                Half-blood   

                                                Skills  
ID                                                      
0                                                  NaN  
1                                                  NaN  
2                                                  NaN  
3                                                  NaN  
4                                                  NaN  
..                                                 ...  
85    Defensive spells, learned with Dumbledore's Army  
86   Revising, being a Prefect, getting the wrong e...  
87    Defensive spells, learned with Dumbledore's Army  
112                          Said to be a great wizard  
125                                                NaN  

[75 rows x 8 columns]

Notice that there is now an extra column titled `Skills`. Pandas automatically added missing values for the instances in the original data since there was not a `Skill` column. Remember that the concat method uses an outer join when combining data.

Now what if instead, we wanted to pull together all four separate dataframes into a new dataframe at one time. Again, there are multiple ways to do this.

**Exercise:** Create a new DataFrame titled `hp_characters2` and add all four DataFrames (`gryffindor`, `slytherin`, `ravenclaw`, and `hufflepuff`) at one time. Try to combine these datasets in one line of code.

In [33]:
hp_characters2 = pd.concat([gryffindor, slytherin, ravenclaw, hufflepuff])
hp_characters2

Name  Gender         Job       House  \
ID                                                                             
0                         Harry James Potter    Male     Student  Gryffindor   
1                      Ronald Bilius Weasley    Male     Student  Gryffindor   
2                      Hermione Jean Granger  Female     Student  Gryffindor   
3    Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                         Neville Longbottom    Male     Student  Gryffindor   
..                                       ...     ...         ...         ...   
85                             Hannah Abbott  Female     Student  Hufflepuff   
86                          Ernest Macmillan    Male     Student  Hufflepuff   
87                               Susan Bones  Female     Student  Hufflepuff   
112                              Edgar Bones    Male         NaN  Hufflepuff   
125                       Edward Remus Lupin    Male     Student  Hufflepuff   

                 Patronus                 Species              Blood status  \
ID                                                                            
0                    Stag                   Human                Half-blood   
1    Jack Russell terrier                   Human                Pure-blood   
2                   Otter                   Human               Muggle-born   
3                 Phoenix                   Human                Half-blood   
4           Non-corporeal                   Human                Pure-blood   
..                    ...                     ...                       ...   
85          Non-corporeal                   Human                Half-blood   
86                   Boar                   Human                Pure-blood   
87                      ?                   Human                Half-blood   
112                     ?                   Human  Pure-blood or half-blood   
125                     ?  Human (Metamorphmagus)                Half-blood   

                                                Skills  
ID                                                      
0                                                  NaN  
1                                                  NaN  
2                                                  NaN  
3                                                  NaN  
4                                                  NaN  
..                                                 ...  
85    Defensive spells, learned with Dumbledore's Army  
86   Revising, being a Prefect, getting the wrong e...  
87    Defensive spells, learned with Dumbledore's Army  
112                          Said to be a great wizard  
125                                                NaN  

[103 rows x 8 columns]

**Exercise:** Combine all four datasets into a new dataframe called `hp_characters3` using a new index. 

In [34]:
hp_characters3 = pd.concat([gryffindor, slytherin, ravenclaw, hufflepuff], ignore_index=True)
hp_characters3

Name  Gender         Job       House  \
0                         Harry James Potter    Male     Student  Gryffindor   
1                      Ronald Bilius Weasley    Male     Student  Gryffindor   
2                      Hermione Jean Granger  Female     Student  Gryffindor   
3    Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                         Neville Longbottom    Male     Student  Gryffindor   
..                                       ...     ...         ...         ...   
98                             Hannah Abbott  Female     Student  Hufflepuff   
99                          Ernest Macmillan    Male     Student  Hufflepuff   
100                              Susan Bones  Female     Student  Hufflepuff   
101                              Edgar Bones    Male         NaN  Hufflepuff   
102                       Edward Remus Lupin    Male     Student  Hufflepuff   

                 Patronus                 Species              Blood status  \
0                    Stag                   Human                Half-blood   
1    Jack Russell terrier                   Human                Pure-blood   
2                   Otter                   Human               Muggle-born   
3                 Phoenix                   Human                Half-blood   
4           Non-corporeal                   Human                Pure-blood   
..                    ...                     ...                       ...   
98          Non-corporeal                   Human                Half-blood   
99                   Boar                   Human                Pure-blood   
100                     ?                   Human                Half-blood   
101                     ?                   Human  Pure-blood or half-blood   
102                     ?  Human (Metamorphmagus)                Half-blood   

                                                Skills  
0                                                  NaN  
1                                                  NaN  
2                                                  NaN  
3                                                  NaN  
4                                                  NaN  
..                                                 ...  
98    Defensive spells, learned with Dumbledore's Army  
99   Revising, being a Prefect, getting the wrong e...  
100   Defensive spells, learned with Dumbledore's Army  
101                          Said to be a great wizard  
102                                                NaN  

[103 rows x 8 columns]

### Dropping Instances

#### Student Practice
Try to perform the following tasks on the indicated dataset. Then check your answers as I walk through the solutions. 

Using the `hp_characters` dataframe we created, let's practice removing instances from the data.

First, we will remove the two incorrect names that were listed in the `Hufflepuff` house data. Let's view the incorrect names by using their index.

In [35]:
# view incorrect names in dataset
hp_characters.loc[[139,140]]

Name Gender        Job       House Patronus Species  \
ID                                                                      
139     Dr. Greg Longo   Male  Professor  Hufflepuff    Eagle   Human   
140  Dr. Mike Morabito   Male  Professor  Hufflepuff    Eagle   Human   

    Blood status                                    Skills  
ID                                                          
139  Muggle-born  Can charm others using Muggle statistics  
140  Muggle-born          Builds robots to fight Voldemort

**Exercise:** Remove Dr. Longo from the dataset using his `ID` number.

In [36]:
hp_characters =  hp_characters.drop(139, axis=0)
hp_characters

Name  Gender         Job       House  \
ID                                                                             
0                         Harry James Potter    Male     Student  Gryffindor   
1                      Ronald Bilius Weasley    Male     Student  Gryffindor   
2                      Hermione Jean Granger  Female     Student  Gryffindor   
3    Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                         Neville Longbottom    Male     Student  Gryffindor   
..                                       ...     ...         ...         ...   
85                             Hannah Abbott  Female     Student  Hufflepuff   
86                          Ernest Macmillan    Male     Student  Hufflepuff   
87                               Susan Bones  Female     Student  Hufflepuff   
112                              Edgar Bones    Male         NaN  Hufflepuff   
125                       Edward Remus Lupin    Male     Student  Hufflepuff   

                 Patronus                 Species              Blood status  \
ID                                                                            
0                    Stag                   Human                Half-blood   
1    Jack Russell terrier                   Human                Pure-blood   
2                   Otter                   Human               Muggle-born   
3                 Phoenix                   Human                Half-blood   
4           Non-corporeal                   Human                Pure-blood   
..                    ...                     ...                       ...   
85          Non-corporeal                   Human                Half-blood   
86                   Boar                   Human                Pure-blood   
87                      ?                   Human                Half-blood   
112                     ?                   Human  Pure-blood or half-blood   
125                     ?  Human (Metamorphmagus)                Half-blood   

                                                Skills  
ID                                                      
0                                                  NaN  
1                                                  NaN  
2                                                  NaN  
3                                                  NaN  
4                                                  NaN  
..                                                 ...  
85    Defensive spells, learned with Dumbledore's Army  
86   Revising, being a Prefect, getting the wrong e...  
87    Defensive spells, learned with Dumbledore's Army  
112                          Said to be a great wizard  
125                                                NaN  

[74 rows x 8 columns]

In [37]:
# view other incorrect entry
hp_characters[hp_characters['Patronus'] == 'Eagle']

Name Gender        Job       House Patronus Species  \
ID                                                                      
140  Dr. Mike Morabito   Male  Professor  Hufflepuff    Eagle   Human   

    Blood status                            Skills  
ID                                                  
140  Muggle-born  Builds robots to fight Voldemort

Dr. Longo is now removed from the dataset. Now, let's remove Dr. Morabito by using his name.

**Exercise:** Remove Dr. Morabito from the dataset but this time using his name. Hint: One way is to do this by filtering your data and saving this filtered data as the DataFrame.

In [38]:
hp_characters = hp_characters[hp_characters['Name'] != 'Dr. Mike Morabito']
hp_characters

Name  Gender         Job       House  \
ID                                                                             
0                         Harry James Potter    Male     Student  Gryffindor   
1                      Ronald Bilius Weasley    Male     Student  Gryffindor   
2                      Hermione Jean Granger  Female     Student  Gryffindor   
3    Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                         Neville Longbottom    Male     Student  Gryffindor   
..                                       ...     ...         ...         ...   
85                             Hannah Abbott  Female     Student  Hufflepuff   
86                          Ernest Macmillan    Male     Student  Hufflepuff   
87                               Susan Bones  Female     Student  Hufflepuff   
112                              Edgar Bones    Male         NaN  Hufflepuff   
125                       Edward Remus Lupin    Male     Student  Hufflepuff   

                 Patronus                 Species              Blood status  \
ID                                                                            
0                    Stag                   Human                Half-blood   
1    Jack Russell terrier                   Human                Pure-blood   
2                   Otter                   Human               Muggle-born   
3                 Phoenix                   Human                Half-blood   
4           Non-corporeal                   Human                Pure-blood   
..                    ...                     ...                       ...   
85          Non-corporeal                   Human                Half-blood   
86                   Boar                   Human                Pure-blood   
87                      ?                   Human                Half-blood   
112                     ?                   Human  Pure-blood or half-blood   
125                     ?  Human (Metamorphmagus)                Half-blood   

                                                Skills  
ID                                                      
0                                                  NaN  
1                                                  NaN  
2                                                  NaN  
3                                                  NaN  
4                                                  NaN  
..                                                 ...  
85    Defensive spells, learned with Dumbledore's Army  
86   Revising, being a Prefect, getting the wrong e...  
87    Defensive spells, learned with Dumbledore's Army  
112                          Said to be a great wizard  
125                                                NaN  

[73 rows x 8 columns]

In [39]:
# confirm that entry was removed
hp_characters[hp_characters['Patronus'] == 'Eagle']

Empty DataFrame
Columns: [Name, Gender, Job, House, Patronus, Species, Blood status, Skills]
Index: []

Now that we have cleaned those instances, there are some other instances that we need to remove. Take a look at the following:

In [40]:
hp_characters[hp_characters['Patronus'] == 'Lion']

Name  Gender                        Job       House  \
ID                                                                      
141    Tywin Lannister    Male  Game of Thrones Character  Gryffindor   
142   Cersei Lannister  Female  Game of Thrones Character  Gryffindor   
143    Jaime Lannister    Male  Game of Thrones Character  Gryffindor   
144   Tyrion Lannister    Male  Game of Thrones Character  Gryffindor   
145  Joffrey Baratheon    Male  Game of Thrones Character  Gryffindor   

    Patronus Species Blood status Skills  
ID                                        
141     Lion   Human  Muggle-born    NaN  
142     Lion   Human  Muggle-born    NaN  
143     Lion   Human  Muggle-born    NaN  
144     Lion   Human  Muggle-born    NaN  
145     Lion   Human  Muggle-born    NaN

It looks like someone accidentally included Game of Thrones names in the dataset. Let's remove them all at once (there are a number of different ways to do this).

**Exercise:** Remove all instances of Game of Thrones characters from the dataset. Use `inplace=True`.

In [41]:
hp_characters.drop([141,142,143,144,145], inplace=True)

<ipython-input-41-fedf312bb83d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hp_characters.drop([141,142,143,144,145], inplace=True)


In [42]:
# or this way...
#hp_characters = hp_characters[hp_characters['Job'] != 'Game of Thrones Character']
#hp_characters

Remember that by using `inplace=True`, you can modify the dataframe without doing an assignment. However, you should be careful when using it. See the links below.

https://stackoverflow.com/questions/45570984/in-pandas-is-inplace-true-considered-harmful-or-not

https://github.com/pandas-dev/pandas/issues/16529

### Adding Columns
So far, we have been adding or removing rows from our DataFrame. Now, let's practice adding columns. 

#### Join
The [join()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html) method joins columns of another DataFrame either on index or on a key column. Let's setup two new DataFrames to check this out.

In [43]:
# create sample DataFrame
df5 = pd.DataFrame({'Animal': ['cat','dog','horse','cow','fox'],
                   'Color': ['white','brown','grey','black','brown']})
df5

Animal  Color
0    cat  white
1    dog  brown
2  horse   grey
3    cow  black
4    fox  brown

In [44]:
# second sample DataFrame
df6 = pd.DataFrame({'Sound': ['meow','bark','neigh','moo',np.nan]})
df6

Sound
0   meow
1   bark
2  neigh
3    moo
4    NaN

In [45]:
# join the two DataFrames based on index
df5.join(df6)

Animal  Color  Sound
0    cat  white   meow
1    dog  brown   bark
2  horse   grey  neigh
3    cow  black    moo
4    fox  brown    NaN

In [46]:
# difference between using append
df5.append(df6)

<ipython-input-46-15bffe5a58a3>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df5.append(df6)


Animal  Color  Sound
0    cat  white    NaN
1    dog  brown    NaN
2  horse   grey    NaN
3    cow  black    NaN
4    fox  brown    NaN
0    NaN    NaN   meow
1    NaN    NaN   bark
2    NaN    NaN  neigh
3    NaN    NaN    moo
4    NaN    NaN    NaN

In [47]:
# using concat, axis=1
pd.concat([df5,df6], axis=1)

Animal  Color  Sound
0    cat  white   meow
1    dog  brown   bark
2  horse   grey  neigh
3    cow  black    moo
4    fox  brown    NaN

In [48]:
# third sample DataFrame but with slightly different index
df7 = pd.DataFrame({'Size': ['small','medium','large','large','huge']}, index=[0,1,2,3,5])
df7

Size
0   small
1  medium
2   large
3   large
5    huge

In [49]:
# notice index 4 and missing index 5
df5.join(df7)

Animal  Color    Size
0    cat  white   small
1    dog  brown  medium
2  horse   grey   large
3    cow  black   large
4    fox  brown     NaN

In [50]:
# using how='right'
df5.join(df7, how='right')

Animal  Color    Size
0    cat  white   small
1    dog  brown  medium
2  horse   grey   large
3    cow  black   large
5    NaN    NaN    huge

#### Merge

See the following regarding the [merge()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html) method from the `Python Data Science Handbook`:

> One essential feature offered by Pandas is its high-performance, in-memory join and merge operations. If you have ever worked with databases, you should be familiar with this type of data interaction. The main interface for this is the pd.merge function

> The behavior implemented in `pd.merge()` is a subset of what is known as relational algebra, which is a formal set of rules for manipulating relational data, and forms the conceptual foundation of operations available in most databases. The strength of the relational algebra approach is that it proposes several primitive operations, which become the building blocks of more complicated operations on any dataset. With this lexicon of fundamental operations implemented efficiently in a database or other program, a wide range of fairly complicated composite operations can be performed. Pandas implements several of these fundamental building-blocks in the `pd.merge()` function and the related `join()` method of Series and Dataframes.

In [51]:
# create sample DataFrame
df1 = pd.DataFrame({'lkey': ['fizz', 'buzz', 'fizzbuzz', 'fizz'],
                    'value': [1, 2, 3, 5]})

df1 

lkey  value
0      fizz      1
1      buzz      2
2  fizzbuzz      3
3      fizz      5

In [52]:
# create other sample DataFrame
df2 = pd.DataFrame({'rkey': ['fizz', 'buzz', 'fizzbuzz', 'fizz'],
                    'value': [5, 6, 7, 8]})
df2

rkey  value
0      fizz      5
1      buzz      6
2  fizzbuzz      7
3      fizz      8

In [53]:
# merge on 'lkey' and 'rkey' columns
df1.merge(df2, left_on='lkey', right_on='rkey')

lkey  value_x      rkey  value_y
0      fizz        1      fizz        5
1      fizz        1      fizz        8
2      fizz        5      fizz        5
3      fizz        5      fizz        8
4      buzz        2      buzz        6
5  fizzbuzz        3  fizzbuzz        7

In [54]:
# specifying suffixes to overlapping columns
df1.merge(df2, left_on='lkey', right_on='rkey',
          suffixes=('_left', '_right'))

lkey  value_left      rkey  value_right
0      fizz           1      fizz            5
1      fizz           1      fizz            8
2      fizz           5      fizz            5
3      fizz           5      fizz            8
4      buzz           2      buzz            6
5  fizzbuzz           3  fizzbuzz            7

In [55]:
# raise an exception if the DataFrames have any overlapping columns.
df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))

ValueError: columns overlap but no suffix specified: Index(['value'], dtype='object')

In [56]:
# let's look at another example
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                             'data2': range(3)})

In [57]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [58]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [59]:
# this is an example of a many-to-one join
# inner join (by default)
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

Notice that for every "b" there was a "1" added to the `data2` column and a "0" added for every "a". It also doesn't include "c" from df1 and "d" from df2.

I didn't specify which column to join on so Pandas uses the overlapping column names as the keys. Although it's good practice to specify (`on='key')`

In [60]:
# left outer join
pd.merge(df1, df2, how='left')

key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0

In [61]:
# right outer join
pd.merge(df1, df2, how='right')

key  data1  data2
0   a    2.0      0
1   a    4.0      0
2   a    5.0      0
3   b    0.0      1
4   b    1.0      1
5   b    6.0      1
6   d    NaN      2

In [62]:
# full outer join
pd.merge(df1, df2, how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [63]:
# creates the cartesian product from both frames
# preserves the order of the left keys
pd.merge(df1, df2, how='cross', suffixes=('_left','_right'))

key_left  data1 key_right  data2
0         b      0         a      0
1         b      0         b      1
2         b      0         d      2
3         b      1         a      0
4         b      1         b      1
5         b      1         d      2
6         a      2         a      0
7         a      2         b      1
8         a      2         d      2
9         c      3         a      0
10        c      3         b      1
11        c      3         d      2
12        a      4         a      0
13        a      4         b      1
14        a      4         d      2
15        a      5         a      0
16        a      5         b      1
17        a      5         d      2
18        b      6         a      0
19        b      6         b      1
20        b      6         d      2

In [64]:
# create two simple DataFrames for card suits and card numbers
suits = pd.DataFrame({'suit': ['clubs','hearts','diamonds','spades']
                       })

numbers = pd.DataFrame({'card_number': ['A','2','3','4','5','6','7','8','9','10','J','Q','K']
                       })

In [65]:
suits

suit
0     clubs
1    hearts
2  diamonds
3    spades

In [66]:
numbers

card_number
0            A
1            2
2            3
3            4
4            5
5            6
6            7
7            8
8            9
9           10
10           J
11           Q
12           K

In [67]:
# what are all the different combination of suits and numbers
deck = pd.merge(suits, numbers, how='cross')
deck

suit card_number
0      clubs           A
1      clubs           2
2      clubs           3
3      clubs           4
4      clubs           5
5      clubs           6
6      clubs           7
7      clubs           8
8      clubs           9
9      clubs          10
10     clubs           J
11     clubs           Q
12     clubs           K
13    hearts           A
14    hearts           2
15    hearts           3
16    hearts           4
17    hearts           5
18    hearts           6
19    hearts           7
20    hearts           8
21    hearts           9
22    hearts          10
23    hearts           J
24    hearts           Q
25    hearts           K
26  diamonds           A
27  diamonds           2
28  diamonds           3
29  diamonds           4
30  diamonds           5
31  diamonds           6
32  diamonds           7
33  diamonds           8
34  diamonds           9
35  diamonds          10
36  diamonds           J
37  diamonds           Q
38  diamonds           K
39    spades           A
40    spades           2
41    spades           3
42    spades           4
43    spades           5
44    spades           6
45    spades           7
46    spades           8
47    spades           9
48    spades          10
49    spades           J
50    spades           Q
51    spades           K

#### Student Practice
<u>Finish the rest of the notebook yourself.</u> Then check your answers as I walk through the solutions. 

Let's now use `join` to add the correct wand to each Harry Potter character.

In [68]:
# first, view the wand data
wand.head()

Wand
ID                                    
0          11"  Holly  phoenix feather
1           12" Ash unicorn tail hair 
2   10¾"  vine wood dragon heartstring
3    15" Elder Thestral tail hair core
4              13" Cherry unicorn hair

In [69]:
wand.shape

(100, 1)

The wand data contains the specific wand descriptions for each character in the Harry Potter dataset listed in ID order.

**Exercise**: Add the `wand` data as a column in the `hp_characters` dataset using the `join()` method.

In [70]:
hp_characters.shape

(68, 8)

In [71]:
#left join is default
hp_characters = hp_characters.join(wand)
hp_characters

Name  Gender         Job       House  \
ID                                                                             
0                         Harry James Potter    Male     Student  Gryffindor   
1                      Ronald Bilius Weasley    Male     Student  Gryffindor   
2                      Hermione Jean Granger  Female     Student  Gryffindor   
3    Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                         Neville Longbottom    Male     Student  Gryffindor   
..                                       ...     ...         ...         ...   
85                             Hannah Abbott  Female     Student  Hufflepuff   
86                          Ernest Macmillan    Male     Student  Hufflepuff   
87                               Susan Bones  Female     Student  Hufflepuff   
112                              Edgar Bones    Male         NaN  Hufflepuff   
125                       Edward Remus Lupin    Male     Student  Hufflepuff   

                 Patronus                 Species              Blood status  \
ID                                                                            
0                    Stag                   Human                Half-blood   
1    Jack Russell terrier                   Human                Pure-blood   
2                   Otter                   Human               Muggle-born   
3                 Phoenix                   Human                Half-blood   
4           Non-corporeal                   Human                Pure-blood   
..                    ...                     ...                       ...   
85          Non-corporeal                   Human                Half-blood   
86                   Boar                   Human                Pure-blood   
87                      ?                   Human                Half-blood   
112                     ?                   Human  Pure-blood or half-blood   
125                     ?  Human (Metamorphmagus)                Half-blood   

                                                Skills  \
ID                                                       
0                                                  NaN   
1                                                  NaN   
2                                                  NaN   
3                                                  NaN   
4                                                  NaN   
..                                                 ...   
85    Defensive spells, learned with Dumbledore's Army   
86   Revising, being a Prefect, getting the wrong e...   
87    Defensive spells, learned with Dumbledore's Army   
112                          Said to be a great wizard   
125                                                NaN   

                                   Wand  
ID                                       
0           11"  Holly  phoenix feather  
1            12" Ash unicorn tail hair   
2    10¾"  vine wood dragon heartstring  
3     15" Elder Thestral tail hair core  
4               13" Cherry unicorn hair  
..                                  ...  
85                              Unknown  
86                              Unknown  
87                              Unknown  
112                             Unknown  
125                             Unknown  

[68 rows x 9 columns]

Now let's take a look at the `color` dataframe. It lists the hair and eye color for each Harry Potter character.

In [72]:
# view color
color.head()

Name              Hair colour  \
ID                                                                     
0                        Harry James Potter                    Black   
1                     Ronald Bilius Weasley                      Red   
2                     Hermione Jean Granger                    Brown   
3   Albus Percival Wulfric Brian Dumbledore  Silver| formerly auburn   
4                        Neville Longbottom                    Blond   

      Eye colour  
ID                
0   Bright green  
1           Blue  
2          Brown  
3           Blue  
4            NaN

In [73]:
color.shape

(139, 3)

**Exercise:** Merge the `color` data with the `hp_characters` DataFrame using the `merge()` method.

In [74]:
#inner join default
hp_characters = pd.merge(hp_characters, color)     #hp_characters.merge(color)
hp_characters

Name  Gender         Job       House  \
0                        Harry James Potter    Male     Student  Gryffindor   
1                     Ronald Bilius Weasley    Male     Student  Gryffindor   
2                     Hermione Jean Granger  Female     Student  Gryffindor   
3   Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                        Neville Longbottom    Male     Student  Gryffindor   
..                                      ...     ...         ...         ...   
63                            Hannah Abbott  Female     Student  Hufflepuff   
64                         Ernest Macmillan    Male     Student  Hufflepuff   
65                              Susan Bones  Female     Student  Hufflepuff   
66                              Edgar Bones    Male         NaN  Hufflepuff   
67                       Edward Remus Lupin    Male     Student  Hufflepuff   

                Patronus                 Species              Blood status  \
0                   Stag                   Human                Half-blood   
1   Jack Russell terrier                   Human                Pure-blood   
2                  Otter                   Human               Muggle-born   
3                Phoenix                   Human                Half-blood   
4          Non-corporeal                   Human                Pure-blood   
..                   ...                     ...                       ...   
63         Non-corporeal                   Human                Half-blood   
64                  Boar                   Human                Pure-blood   
65                     ?                   Human                Half-blood   
66                     ?                   Human  Pure-blood or half-blood   
67                     ?  Human (Metamorphmagus)                Half-blood   

                                               Skills  \
0                                                 NaN   
1                                                 NaN   
2                                                 NaN   
3                                                 NaN   
4                                                 NaN   
..                                                ...   
63   Defensive spells, learned with Dumbledore's Army   
64  Revising, being a Prefect, getting the wrong e...   
65   Defensive spells, learned with Dumbledore's Army   
66                          Said to be a great wizard   
67                                                NaN   

                                  Wand              Hair colour    Eye colour  
0          11"  Holly  phoenix feather                    Black  Bright green  
1           12" Ash unicorn tail hair                       Red          Blue  
2   10¾"  vine wood dragon heartstring                    Brown         Brown  
3    15" Elder Thestral tail hair core  Silver| formerly auburn          Blue  
4              13" Cherry unicorn hair                    Blond           NaN  
..                                 ...                      ...           ...  
63                             Unknown                   Blonde         Brown  
64                             Unknown                    Blond           NaN  
65                             Unknown                      NaN           NaN  
66                             Unknown            Reddish-brown          Grey  
67                             Unknown                 Variable      Variable  

[68 rows x 11 columns]

There is also data from non-Hogwart's House characters (ie those not in Gryffindor, Slytherin, Raveclaw or Hufflepuff) but it has been separated into two different datasets. Let's take a look at them now.

In [75]:
other1.head()

Name  Gender  \
ID                             
70    Cuthbert Binns    Male   
71  Barty Crouch Jr.    Male   
72   Charity Burbage  Female   
73           Firenze    Male   
92    Igor Karkaroff    Male   

                                                  Job  House  
ID                                                            
70                     Professor of History of Magic     NaN  
71  Professor of Defence Against the Dark Arts (as...    NaN  
72                        Professor of Muggle Studies    NaN  
73                            Professor of Divination    NaN  
92                 Headmaster of Durmstrang Institute    NaN

In [76]:
other2.head()

Given Name       Patronus  Species              Blood status  \
ID                                                                       
70    Cuthbert Binns        Unknown    Ghost                       NaN   
71  Barty Crouch Jr.        Unknown    Human  Pure-blood or half-blood   
72   Charity Burbage  Non-corporeal    Human  Pure-blood or half-blood   
73           Firenze            NaN  Centaur                       NaN   
92    Igor Karkaroff           None    Human  Pure-blood or Half-blood   

       Wand          Eye colour             Hair colour  
ID                                                       
70  Unknown               Black         White (balding)  
71  Unknown      Pale, freckled             Straw blond  
72  Unknown                 NaN                  Blonde  
73      NaN  Astonishingly blue             White-blond  
92  Unknown                 NaN  Silver| formerly black

**Exercise:** Using `merge()` combine the `other1` and `other2` data into a new dataframe called `other_characters` keeping the respective `ID` for each instance. (check the Pandas documentation if you need help)

In [77]:
other_characters = pd.merge(other1, other2, left_index=True, right_index=True)
other_characters

Name  Gender  \
ID                                      
70             Cuthbert Binns    Male   
71           Barty Crouch Jr.    Male   
72            Charity Burbage  Female   
73                    Firenze    Male   
92             Igor Karkaroff    Male   
93       Kingsley Shacklebolt    Male   
94              Alastor Moody    Male   
95           Alice Longbottom  Female   
97           Rufus Scrimgeour    Male   
98     Cornelius Oswald Fudge    Male   
99           Barty Crouch Sr.    Male   
100              Amos Diggory    Male   
101            Dedalus Diggle    Male   
102              Elphias Doge    Male   
104      Aberforth Dumbledore    Male   
105        Mundungus Fletcher    Male   
106           Sturgis Podmore    Male   
107              Hestia Jones  Female   
108          Marlene McKinnon  Female   
109            Fabian Prewett    Male   
110            Gideon Prewett    Male   
111            Emmeline Vance  Female   
113           Dorcas Meadowes  Female   
114             Benjy Fenwick    Male   
118           Petunia Dursley  Female   
119            Vernon Dursley    Male   
120            Dudley Dursley    Male   
121             Marge Dursley  Female   
128               Argus Filch    Male   
129             Poppy Pomfrey  Female   
130             Rolanda Hooch  Female   
131                Irma Pince  Female   
132           Aurora Sinistra  Female   
133            Septima Vector  Female   
134  Wilhelmina Grubbly-Plank  Female   
135           Fenrir Greyback    Male   
136       Gellert Grindelwald    Male   
137                     Dobby    Male   
138                  Kreacher    Male   

                                                   Job  House  \
ID                                                              
70                      Professor of History of Magic     NaN   
71   Professor of Defence Against the Dark Arts (as...    NaN   
72                         Professor of Muggle Studies    NaN   
73                             Professor of Divination    NaN   
92                  Headmaster of Durmstrang Institute    NaN   
93                         Auror  | Minister for Magic    NaN   
94                                              Auror     NaN   
95                                               Auror    NaN   
97            Head of Auror Office| Minister for Magic    NaN   
98                                  Minister for Magic    NaN   
99   Head of the Department of International Magica...    NaN   
100  Employee of the Department for the Regulation ...    NaN   
101                                                NaN    NaN   
102                  Special Advisor to the Wizengamot    NaN   
104             Owner and Barman of the Hog's Head Inn    NaN   
105                      Dealer of wizarding artifacts    NaN   
106                                      Advance Guard    NaN   
107                                      Advance Guard    NaN   
108                                                NaN    NaN   
109                                                NaN    NaN   
110                                                NaN    NaN   
111                                      Advance Guard    NaN   
113                                                NaN    NaN   
114                                                NaN    NaN   
118                                                NaN    NaN   
119                              Director at Grunnings    NaN   
120                                                NaN    NaN   
121                                        Dog breeder    NaN   
128                              Caretaker of Hogwarts    NaN   
129                          Matron at Hogwarts School    NaN   
130                      Flying Instructor at Hogwarts    NaN   
131                              Librarian at Hogwarts    NaN   
132                             Astronomer at Hogwarts    NaN   
133                 Professor of Arithmancyat Hogwarts    NaN   
134

Notice that both `Name` and `Given Name` is in the new DataFrame. Since this is providing duplicate information you could now remove one of the columns. 

**Bonus Exercise:** Merge the `other1` and `other2` data the same as above but also removing the `Given Name` field. Try to do this in one line of code.

In [78]:
other_characters = pd.merge(other1, other2, left_index=True, right_index=True).drop('Given Name', axis=1)
other_characters

Name  Gender  \
ID                                      
70             Cuthbert Binns    Male   
71           Barty Crouch Jr.    Male   
72            Charity Burbage  Female   
73                    Firenze    Male   
92             Igor Karkaroff    Male   
93       Kingsley Shacklebolt    Male   
94              Alastor Moody    Male   
95           Alice Longbottom  Female   
97           Rufus Scrimgeour    Male   
98     Cornelius Oswald Fudge    Male   
99           Barty Crouch Sr.    Male   
100              Amos Diggory    Male   
101            Dedalus Diggle    Male   
102              Elphias Doge    Male   
104      Aberforth Dumbledore    Male   
105        Mundungus Fletcher    Male   
106           Sturgis Podmore    Male   
107              Hestia Jones  Female   
108          Marlene McKinnon  Female   
109            Fabian Prewett    Male   
110            Gideon Prewett    Male   
111            Emmeline Vance  Female   
113           Dorcas Meadowes  Female   
114             Benjy Fenwick    Male   
118           Petunia Dursley  Female   
119            Vernon Dursley    Male   
120            Dudley Dursley    Male   
121             Marge Dursley  Female   
128               Argus Filch    Male   
129             Poppy Pomfrey  Female   
130             Rolanda Hooch  Female   
131                Irma Pince  Female   
132           Aurora Sinistra  Female   
133            Septima Vector  Female   
134  Wilhelmina Grubbly-Plank  Female   
135           Fenrir Greyback    Male   
136       Gellert Grindelwald    Male   
137                     Dobby    Male   
138                  Kreacher    Male   

                                                   Job  House       Patronus  \
ID                                                                             
70                      Professor of History of Magic     NaN        Unknown   
71   Professor of Defence Against the Dark Arts (as...    NaN        Unknown   
72                         Professor of Muggle Studies    NaN  Non-corporeal   
73                             Professor of Divination    NaN            NaN   
92                  Headmaster of Durmstrang Institute    NaN           None   
93                         Auror  | Minister for Magic    NaN           Lynx   
94                                              Auror     NaN  Non-corporeal   
95                                               Auror    NaN        Unknown   
97            Head of Auror Office| Minister for Magic    NaN  Non-corporeal   
98                                  Minister for Magic    NaN  Non-corporeal   
99   Head of the Department of International Magica...    NaN  Non-corporeal   
100  Employee of the Department for the Regulation ...    NaN  Non-corporeal   
101                                                NaN    NaN  Non-corporeal   
102                  Special Advisor to the Wizengamot    NaN  Non-corporeal   
104             Owner and Barman of the Hog's Head Inn    NaN           Goat   
105                      Dealer of wizarding artifacts    NaN  Non-corporeal   
106                                      Advance Guard    NaN        Unknown   
107                                      Advance Guard    NaN        Unknown   
108                                                NaN    NaN        Unknown   
109                                                NaN    NaN        Unknown   
110                                                NaN    NaN        Unknown   
111                                      Advance Guard    NaN        Unknown   
113                                                NaN    NaN        Unknown   
114                                                NaN    NaN        Unknown   
118                                                NaN    NaN            NaN   
119                              Director at Grunnings    NaN            NaN   
120                                                NaN    NaN            NaN   
121                    

**Exercise:** Add `other_characters` to the `hp_characters` DataFrame.

In [79]:
hp_characters = hp_characters.append(other_characters)
hp_characters

<ipython-input-79-15c4c3b1f364>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  hp_characters = hp_characters.append(other_characters)


Name  Gender  \
0                         Harry James Potter    Male   
1                      Ronald Bilius Weasley    Male   
2                      Hermione Jean Granger  Female   
3    Albus Percival Wulfric Brian Dumbledore    Male   
4                         Neville Longbottom    Male   
..                                       ...     ...   
134                 Wilhelmina Grubbly-Plank  Female   
135                          Fenrir Greyback    Male   
136                      Gellert Grindelwald    Male   
137                                    Dobby    Male   
138                                 Kreacher    Male   

                                                   Job       House  \
0                                              Student  Gryffindor   
1                                              Student  Gryffindor   
2                                              Student  Gryffindor   
3                                           Headmaster  Gryffindor   
4                                              Student  Gryffindor   
..                                                 ...         ...   
134  Substitute professor of Care of Magical Creatu...         NaN   
135                                                NaN         NaN   
136           Revolutionary leader(c. 1920s[6]  1945)         NaN   
137  Malfoy family's house-elf (? - 1993),\nHogwart...         NaN   
138  \nBlack family's house-elf (?-1996), \nHarry P...         NaN   

                 Patronus    Species              Blood status Skills  \
0                    Stag      Human                Half-blood    NaN   
1    Jack Russell terrier      Human                Pure-blood    NaN   
2                   Otter      Human               Muggle-born    NaN   
3                 Phoenix      Human                Half-blood    NaN   
4           Non-corporeal      Human                Pure-blood    NaN   
..                    ...        ...                       ...    ...   
134         Non-corporeal     Human                        NaN    NaN   
135                  None   Werewolf                       NaN    NaN   
136                   NaN     Human   Pure-blood or half-blood    NaN   
137                   NaN  House elf                       NaN    NaN   
138                   NaN  House elf                       NaN    NaN   

                                    Wand              Hair colour  \
0            11"  Holly  phoenix feather                    Black   
1             12" Ash unicorn tail hair                       Red   
2     10¾"  vine wood dragon heartstring                    Brown   
3      15" Elder Thestral tail hair core  Silver| formerly auburn   
4                13" Cherry unicorn hair                    Blond   
..                                   ...                      ...   
134                              Unknown                     Grey   
135                              Unknown                     Grey   
136  15", Elder, Thestral tail hair core                    Blond   
137                                  NaN                    Green   
138                                  NaN                    White   

       Eye colour  
0    Bright green  
1            Blue  
2           Brown  
3            Blue  
4             NaN  
..            ...  
134           NaN  
135           NaN  
136          Blue  
137           NaN  
138           NaN  

[107 rows x 11 columns]

**Bonus Exercise**:

After merging all the data, we noticed a **big mistake**! Hagrid, one of our favorite characters, is missing from the data. Here is his information:

- **Name**: Rubeus Hagrid
- **Gender**: Male
- **Job**: Keeper of Keys and Grounds | Professor of Care of Magical Creatures
- **House**: Gryffindor
- **Patronus**: None
- **Species**: Half-Human/Half-Giant
- **Blood status**: Part-Human (Half-giant)
- **Wand**: 16" Oak unknown core
- **Hair colour**: Black
- **Eye colour**: Black

Add Hagrid to the `hp_characters` dataset. (try to Google how to do this if needed, then watch the solutions video for one option)

In [86]:
hp_characters.tail()

Name Gender  \
103      Fenrir Greyback   Male   
104  Gellert Grindelwald   Male   
105                Dobby   Male   
106             Kreacher   Male   
107        Rubeus Hagrid   Male   

                                                   Job       House Patronus  \
103                                                NaN         NaN     None   
104           Revolutionary leader(c. 1920s[6]  1945)         NaN      NaN   
105  Malfoy family's house-elf (? - 1993),\nHogwart...         NaN      NaN   
106  \nBlack family's house-elf (?-1996), \nHarry P...         NaN      NaN   
107  Keeper of Keys and Grounds | Professor of Care...  Gryffindor     None   

                   Species              Blood status Skills  \
103               Werewolf                       NaN    NaN   
104                 Human   Pure-blood or half-blood    NaN   
105              House elf                       NaN    NaN   
106              House elf                       NaN    NaN   
107  Half-Human/Half-Giant   Part-Human (Half-giant)    NaN   

                                    Wand Hair colour Eye colour  
103                              Unknown        Grey        NaN  
104  15", Elder, Thestral tail hair core       Blond       Blue  
105                                  NaN       Green        NaN  
106                                  NaN       White        NaN  
107                 16" Oak unknown core       Black      Black

In [87]:
hp_characters.shape

(108, 11)

In [83]:
hagrid_row = { 
'Name': 'Rubeus Hagrid',
'Gender': 'Male',
'Job': 'Keeper of Keys and Grounds | Professor of Care of Magical Creatures',
'House': 'Gryffindor',
'Patronus': None,
'Species': 'Half-Human/Half-Giant',
'Blood status': 'Part-Human (Half-giant)',
'Wand': '16" Oak unknown core',
'Hair colour': 'Black',
'Eye colour': 'Black' }


hp_characters = hp_characters.append(hagrid_row, ignore_index=True)
hp_characters

<ipython-input-83-e80ede027847>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  hp_characters = hp_characters.append(hagrid_row, ignore_index=True)


Name  Gender  \
0                         Harry James Potter    Male   
1                      Ronald Bilius Weasley    Male   
2                      Hermione Jean Granger  Female   
3    Albus Percival Wulfric Brian Dumbledore    Male   
4                         Neville Longbottom    Male   
..                                       ...     ...   
103                          Fenrir Greyback    Male   
104                      Gellert Grindelwald    Male   
105                                    Dobby    Male   
106                                 Kreacher    Male   
107                            Rubeus Hagrid    Male   

                                                   Job       House  \
0                                              Student  Gryffindor   
1                                              Student  Gryffindor   
2                                              Student  Gryffindor   
3                                           Headmaster  Gryffindor   
4                                              Student  Gryffindor   
..                                                 ...         ...   
103                                                NaN         NaN   
104           Revolutionary leader(c. 1920s[6]  1945)         NaN   
105  Malfoy family's house-elf (? - 1993),\nHogwart...         NaN   
106  \nBlack family's house-elf (?-1996), \nHarry P...         NaN   
107  Keeper of Keys and Grounds | Professor of Care...  Gryffindor   

                 Patronus                Species              Blood status  \
0                    Stag                  Human                Half-blood   
1    Jack Russell terrier                  Human                Pure-blood   
2                   Otter                  Human               Muggle-born   
3                 Phoenix                  Human                Half-blood   
4           Non-corporeal                  Human                Pure-blood   
..                    ...                    ...                       ...   
103                  None               Werewolf                       NaN   
104                   NaN                 Human   Pure-blood or half-blood   
105                   NaN              House elf                       NaN   
106                   NaN              House elf                       NaN   
107                  None  Half-Human/Half-Giant   Part-Human (Half-giant)   

    Skills                                 Wand              Hair colour  \
0      NaN          11"  Holly  phoenix feather                    Black   
1      NaN           12" Ash unicorn tail hair                       Red   
2      NaN   10¾"  vine wood dragon heartstring                    Brown   
3      NaN    15" Elder Thestral tail hair core  Silver| formerly auburn   
4      NaN              13" Cherry unicorn hair                    Blond   
..     ...                                  ...                      ...   
103    NaN                              Unknown                     Grey   
104    NaN  15", Elder, Thestral tail hair core                    Blond   
105    NaN                                  NaN                    Green   
106    NaN                                  NaN                    White   
107    NaN                 16" Oak unknown core                    Black   

       Eye colour  
0    Bright green  
1            Blue  
2           Brown  
3            Blue  
4             NaN  
..            ...  
103           NaN  
104          Blue  
105           NaN  
106           NaN  
107         Black  

[108 rows x 11 columns]

Next, view the `dead_characters` DataFrame which includes the date of death for any deceased characters.

In [88]:
# view dataframe
dead_characters.head()

Name             Death
ID                                                           
3   Albus Percival Wulfric Brian Dumbledore    30 June, 1997 
5                              Fred Weasley       2 May, 1998
10                           Lily J. Potter  31 October, 1981
11                             James Potter  31 October, 1981
12                             Sirius Black     18 June, 1996

**Exercise:** Create a DataFrame called `hp_dead_characters` using the `hp_characters` and `dead_characters` DataFrames. This new DataFrame should only include characters that are deceased. Don't worry about preserving index numbers.

In [91]:
hp_dead_characters = pd.merge(hp_characters,dead_characters, how='right' )  
hp_dead_characters

Name  Gender  \
0    Albus Percival Wulfric Brian Dumbledore    Male   
1                               Fred Weasley    Male   
2                             Lily J. Potter  Female   
3                               James Potter    Male   
4                               Sirius Black    Male   
5                           Remus John Lupin    Male   
6                            Peter Pettigrew    Male   
7                             Lavender Brown  Female   
8                              Colin Creevey    Male   
9                          Quirinus Quirrell    Male   
10  Myrtle Elizabeth Warren (Moaning Myrtle)  Female   
11                             Severus Snape     NaN   
12                            Vincent Crabbe     NaN   
13                       Bellatrix Lestrange     NaN   
14                    Regulus Arcturus Black     NaN   
15                        Tom Marvolo Riddle     NaN   
16                              Bloody Baron     NaN   
17                         Salazar Slytherin     NaN   
18                         Godric Gryffindor    Male   
19                          Rowena Ravenclaw  Female   
20              Nicholas de Mimsy-Porpington    Male   
21                            Cuthbert Binns    Male   
22                          Barty Crouch Jr.    Male   
23                           Charity Burbage  Female   
24                          Helga Hufflepuff  Female   
25                                 Fat Friar    Male   
26                          Helena Ravenclaw  Female   
27                          Nymphadora Tonks  Female   
28                            Cedric Diggory    Male   
29                            Igor Karkaroff    Male   
30                             Alastor Moody    Male   
31                          Rufus Scrimgeour    Male   
32                          Barty Crouch Sr.    Male   
33                          Marlene McKinnon  Female   
34                            Fabian Prewett    Male   
35                            Gideon Prewett    Male   
36                            Emmeline Vance  Female   
37                               Edgar Bones    Male   
38                           Dorcas Meadowes  Female   
39                             Benjy Fenwick    Male   
40                       Gellert Grindelwald    Male   
41                                     Dobby    Male   

                                                  Job       House  \
0                                          Headmaster  Gryffindor   
1                                             Student  Gryffindor   
2                                                 NaN  Gryffindor   
3                                                 NaN  Gryffindor   
4                                                 NaN  Gryffindor   
5         Professor of Defence Against the Dark Arts   Gryffindor   
6                       The Servant of Lord Voldemort  Gryffindor   
7                                             Student  Gryffindor   
8                                             Student  Gryffindor   
9            Defence Against the Dark Arts(1991-1992)   Ravenclaw   
10                                            Student   Ravenclaw   
11                                                NaN         NaN   
12                                                NaN         NaN   
13                                                NaN         NaN   
14                                                NaN         NaN   
15                                                NaN         NaN   
16                                                NaN         NaN   
17                                                NaN         NaN   
18                              Founder of Gryffindor  Gryffindor   
19                               Founder of Ravenclaw   Ravenclaw   
20                             Gryffindor House Ghost  Gryffindor   
21                     Professor of History of Magic          NaN   
22  Professor of Defence Against the Dark Ar

Next, look at the `loyalty` DataFrame. This includes a list of all characters with stated allegiance to Voldemort.

In [92]:
# view loyalty
loyalty.head()

Name                         Loyalty
ID                                                     
14      Peter Pettigrew    Lord Voldemort| Death Eaters
31    Quirinus Quirrell                  Lord Voldemort
48  Bellatrix Lestrange  Lord Voldemort  | Death Eaters
51        Lucius Malfoy  Lord Voldemort  | Death Eaters
52      Narcissa Malfoy  Lord Voldemort  | Death Eaters

**Exercise:** Create a DataFrame called `voldemort_army` that includes only characters loyal to Voldemort. Again, you don't need to preserve index numbers.

In [97]:
voldemort_army = pd.merge(hp_characters, loyalty, how='right')
voldemort_army

Name Gender  \
0       Peter Pettigrew   Male   
1     Quirinus Quirrell   Male   
2   Bellatrix Lestrange    NaN   
3         Lucius Malfoy    NaN   
4       Narcissa Malfoy    NaN   
5   Rodolphus Lestrange    NaN   
6      Barty Crouch Jr.   Male   
7         Alecto Carrow    NaN   
8         Amycus Carrow    NaN   
9        Walden Macnair    NaN   
10    Augustus Rookwood    NaN   
11      Antonin Dolohov    NaN   
12        Corban Yaxley    NaN   
13      Fenrir Greyback   Male   

                                                  Job       House  \
0                       The Servant of Lord Voldemort  Gryffindor   
1            Defence Against the Dark Arts(1991-1992)   Ravenclaw   
2                                                 NaN         NaN   
3                                                 NaN         NaN   
4                                                 NaN         NaN   
5                                                 NaN         NaN   
6   Professor of Defence Against the Dark Arts (as...         NaN   
7                                                 NaN         NaN   
8                                                 NaN         NaN   
9                                                 NaN         NaN   
10                                                NaN         NaN   
11                                                NaN         NaN   
12                                                NaN         NaN   
13                                                NaN         NaN   

         Patronus   Species              Blood status Skills  \
0            None     Human  Half-blood or pure-blood    NaN   
1   Non-corporeal     Human                Half-blood    NaN   
2             NaN       NaN                       NaN    NaN   
3             NaN       NaN                       NaN    NaN   
4             NaN       NaN                       NaN    NaN   
5             NaN       NaN                       NaN    NaN   
6         Unknown     Human  Pure-blood or half-blood    NaN   
7             NaN       NaN                       NaN    NaN   
8             NaN       NaN                       NaN    NaN   
9             NaN       NaN                       NaN    NaN   
10            NaN       NaN                       NaN    NaN   
11            NaN       NaN                       NaN    NaN   
12            NaN       NaN                       NaN    NaN   
13           None  Werewolf                       NaN    NaN   

                               Wand             Hair colour      Eye colour  \
0   9¼" Chestnut dragon heartstring  Colourless and balding            Blue   
1       9" Alder unicorn hair bendy                     NaN             NaN   
2                               NaN                     NaN             NaN   
3                               NaN                     NaN             NaN   
4                               NaN                     NaN             NaN   
5                               NaN                     NaN             NaN   
6                           Unknown             Straw blond  Pale, freckled   
7                               NaN                     NaN             NaN   
8                               NaN                     NaN             NaN   
9                               NaN                     NaN             NaN   
10                              NaN                     NaN             NaN   
11                              NaN                     NaN             NaN   
12                              NaN                     NaN             NaN   
13                          Unknown                    Grey             NaN   

                           Loyalty  
0     Lord Voldemort| Death Eaters  
1                   Lord Voldemort  
2   Lord Voldemort  | Death Eaters  
3   Lord Voldemort  | Death Eaters  
4   Lord Voldemort  | Death Eaters  
5   Lord Voldemort  | Death Eaters  
6   Lord Voldemort  | Death Eaters  
7   Lord Voldemort  | Death E

Now take a look at the `gryffindor_bloodstatus` and `gryffindor_species` dataframes.

In [98]:
gryffindor_bloodstatus.head()

Name         Type
ID                                                      
0                        Harry James Potter   Half-blood
1                     Ronald Bilius Weasley   Pure-blood
2                     Hermione Jean Granger  Muggle-born
3   Albus Percival Wulfric Brian Dumbledore   Half-blood
4                        Neville Longbottom   Pure-blood

In [99]:
gryffindor_species.head()

Name  Gender         Job       House  \
ID                                                                            
0                        Harry James Potter    Male     Student  Gryffindor   
1                     Ronald Bilius Weasley    Male     Student  Gryffindor   
2                     Hermione Jean Granger  Female     Student  Gryffindor   
3   Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                        Neville Longbottom    Male     Student  Gryffindor   

     Type  
ID         
0   Human  
1   Human  
2   Human  
3   Human  
4   Human

**Exercise:** Merge these two DataFrames together into a new DataFrame called `gryffindor2`. Notice that they both have a column called `Type` that represents different attributes. Add a suffix to the `Type` attributes so we better understand what each attribute represents.

In [100]:
#merge with 2 columns with same name w/o specifying suffix
pd.merge(gryffindor_bloodstatus, gryffindor_species, on='Name').head()

Name       Type_x  Gender         Job  \
0                       Harry James Potter   Half-blood    Male     Student   
1                    Ronald Bilius Weasley   Pure-blood    Male     Student   
2                    Hermione Jean Granger  Muggle-born  Female     Student   
3  Albus Percival Wulfric Brian Dumbledore   Half-blood    Male  Headmaster   
4                       Neville Longbottom   Pure-blood    Male     Student   

        House Type_y  
0  Gryffindor  Human  
1  Gryffindor  Human  
2  Gryffindor  Human  
3  Gryffindor  Human  
4  Gryffindor  Human

In [102]:
#now mergiing while giving the two columns with the same name a seperate suffix
gryffindor2 = pd.merge(gryffindor_bloodstatus, gryffindor_species, on='Name', suffixes=('_bloodstatus', '_species'))
gryffindor2.head()

Name Type_bloodstatus  Gender  \
0                       Harry James Potter       Half-blood    Male   
1                    Ronald Bilius Weasley       Pure-blood    Male   
2                    Hermione Jean Granger      Muggle-born  Female   
3  Albus Percival Wulfric Brian Dumbledore       Half-blood    Male   
4                       Neville Longbottom       Pure-blood    Male   

          Job       House Type_species  
0     Student  Gryffindor        Human  
1     Student  Gryffindor        Human  
2     Student  Gryffindor        Human  
3  Headmaster  Gryffindor        Human  
4     Student  Gryffindor        Human

### Removing Columns

Now that we've had practice adding columns and merging dataframes. Let's practice removing columns.

In [103]:
# refresh DataFrame
hp_characters.head()

Name  Gender         Job       House  \
0                       Harry James Potter    Male     Student  Gryffindor   
1                    Ronald Bilius Weasley    Male     Student  Gryffindor   
2                    Hermione Jean Granger  Female     Student  Gryffindor   
3  Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                       Neville Longbottom    Male     Student  Gryffindor   

               Patronus Species Blood status Skills  \
0                  Stag   Human   Half-blood    NaN   
1  Jack Russell terrier   Human   Pure-blood    NaN   
2                 Otter   Human  Muggle-born    NaN   
3               Phoenix   Human   Half-blood    NaN   
4         Non-corporeal   Human   Pure-blood    NaN   

                                 Wand              Hair colour    Eye colour  
0         11"  Holly  phoenix feather                    Black  Bright green  
1          12" Ash unicorn tail hair                       Red          Blue  
2  10¾"  vine wood dragon heartstring                    Brown         Brown  
3   15" Elder Thestral tail hair core  Silver| formerly auburn          Blue  
4             13" Cherry unicorn hair                    Blond           NaN

**Exercise:** Since the `Skills` column is mostly filled with null values, remove this column from the `hp_characters` DataFrame.

In [105]:
hp_characters = hp_characters.drop('Skills', axis=1)
hp_characters

Name  Gender  \
0                         Harry James Potter    Male   
1                      Ronald Bilius Weasley    Male   
2                      Hermione Jean Granger  Female   
3    Albus Percival Wulfric Brian Dumbledore    Male   
4                         Neville Longbottom    Male   
..                                       ...     ...   
103                          Fenrir Greyback    Male   
104                      Gellert Grindelwald    Male   
105                                    Dobby    Male   
106                                 Kreacher    Male   
107                            Rubeus Hagrid    Male   

                                                   Job       House  \
0                                              Student  Gryffindor   
1                                              Student  Gryffindor   
2                                              Student  Gryffindor   
3                                           Headmaster  Gryffindor   
4                                              Student  Gryffindor   
..                                                 ...         ...   
103                                                NaN         NaN   
104           Revolutionary leader(c. 1920s[6]  1945)         NaN   
105  Malfoy family's house-elf (? - 1993),\nHogwart...         NaN   
106  \nBlack family's house-elf (?-1996), \nHarry P...         NaN   
107  Keeper of Keys and Grounds | Professor of Care...  Gryffindor   

                 Patronus                Species              Blood status  \
0                    Stag                  Human                Half-blood   
1    Jack Russell terrier                  Human                Pure-blood   
2                   Otter                  Human               Muggle-born   
3                 Phoenix                  Human                Half-blood   
4           Non-corporeal                  Human                Pure-blood   
..                    ...                    ...                       ...   
103                  None               Werewolf                       NaN   
104                   NaN                 Human   Pure-blood or half-blood   
105                   NaN              House elf                       NaN   
106                   NaN              House elf                       NaN   
107                  None  Half-Human/Half-Giant   Part-Human (Half-giant)   

                                    Wand              Hair colour  \
0            11"  Holly  phoenix feather                    Black   
1             12" Ash unicorn tail hair                       Red   
2     10¾"  vine wood dragon heartstring                    Brown   
3      15" Elder Thestral tail hair core  Silver| formerly auburn   
4                13" Cherry unicorn hair                    Blond   
..                                   ...                      ...   
103                              Unknown                     Grey   
104  15", Elder, Thestral tail hair core                    Blond   
105                                  NaN                    Green   
106                                  NaN                    White   
107                 16" Oak unknown core                    Black   

       Eye colour  
0    Bright green  
1            Blue  
2           Brown  
3            Blue  
4             NaN  
..            ...  
103           NaN  
104          Blue  
105           NaN  
106           NaN  
107         Black  

[108 rows x 10 columns]

### Updating Value in DataFrame

Notice that some values are labeled with a `?`. These are values where the data is unknown...in other words, the books or movies never mention it.

In [106]:
# see Fred and George Weasley's Patronus column as an example
hp_characters.head(10)

Name  Gender         Job       House  \
0                       Harry James Potter    Male     Student  Gryffindor   
1                    Ronald Bilius Weasley    Male     Student  Gryffindor   
2                    Hermione Jean Granger  Female     Student  Gryffindor   
3  Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                       Neville Longbottom    Male     Student  Gryffindor   
5                             Fred Weasley    Male     Student  Gryffindor   
6                           George Weasley    Male     Student  Gryffindor   
7            Ginevra (Ginny) Molly Weasley  Female     Student  Gryffindor   
8                              Dean Thomas    Male     Student  Gryffindor   
9                          Seamus Finnigan    Male     Student  Gryffindor   

               Patronus Species Blood status  \
0                  Stag   Human   Half-blood   
1  Jack Russell terrier   Human   Pure-blood   
2                 Otter   Human  Muggle-born   
3               Phoenix   Human   Half-blood   
4         Non-corporeal   Human   Pure-blood   
5                     ?   Human   Pure-blood   
6                     ?   Human   Pure-blood   
7                 Horse   Human   Pure-blood   
8                     ?   Human  Muggle-born   
9                   Fox   Human   Half-blood   

                                 Wand              Hair colour    Eye colour  
0         11"  Holly  phoenix feather                    Black  Bright green  
1          12" Ash unicorn tail hair                       Red          Blue  
2  10¾"  vine wood dragon heartstring                    Brown         Brown  
3   15" Elder Thestral tail hair core  Silver| formerly auburn          Blue  
4             13" Cherry unicorn hair                    Blond           NaN  
5                             Unknown                      Red         Brown  
6                             Unknown                      Red         Brown  
7                             Unknown                      Red  Bright brown  
8                             Unknown                    Black         Brown  
9                             Unknown                    Sandy           NaN

**Exercise:** Change all values of `?` to the string `'Unknown'` to better represent what this data means.

In [108]:
hp_characters = hp_characters.replace('?', 'Uknown')
hp_characters.head(10)

Name  Gender         Job       House  \
0                       Harry James Potter    Male     Student  Gryffindor   
1                    Ronald Bilius Weasley    Male     Student  Gryffindor   
2                    Hermione Jean Granger  Female     Student  Gryffindor   
3  Albus Percival Wulfric Brian Dumbledore    Male  Headmaster  Gryffindor   
4                       Neville Longbottom    Male     Student  Gryffindor   
5                             Fred Weasley    Male     Student  Gryffindor   
6                           George Weasley    Male     Student  Gryffindor   
7            Ginevra (Ginny) Molly Weasley  Female     Student  Gryffindor   
8                              Dean Thomas    Male     Student  Gryffindor   
9                          Seamus Finnigan    Male     Student  Gryffindor   

               Patronus Species Blood status  \
0                  Stag   Human   Half-blood   
1  Jack Russell terrier   Human   Pure-blood   
2                 Otter   Human  Muggle-born   
3               Phoenix   Human   Half-blood   
4         Non-corporeal   Human   Pure-blood   
5                Uknown   Human   Pure-blood   
6                Uknown   Human   Pure-blood   
7                 Horse   Human   Pure-blood   
8                Uknown   Human  Muggle-born   
9                   Fox   Human   Half-blood   

                                 Wand              Hair colour    Eye colour  
0         11"  Holly  phoenix feather                    Black  Bright green  
1          12" Ash unicorn tail hair                       Red          Blue  
2  10¾"  vine wood dragon heartstring                    Brown         Brown  
3   15" Elder Thestral tail hair core  Silver| formerly auburn          Blue  
4             13" Cherry unicorn hair                    Blond           NaN  
5                             Unknown                      Red         Brown  
6                             Unknown                      Red         Brown  
7                             Unknown                      Red  Bright brown  
8                             Unknown                    Black         Brown  
9                             Unknown                    Sandy           NaN

### Renaming Columns

The data has the British spelling for colour. Since this data will be used in the US, we should rename these columns.

**Exercise:** Rename the word `colour` to `color` in the respective columns for the `hp_characters` dataframe.

In [110]:
hp_characters = hp_characters.rename({'Hair colour': 'Hair color', 'Eye colour': 'Eye color'}, axis=1)
hp_characters

Name  Gender  \
0                         Harry James Potter    Male   
1                      Ronald Bilius Weasley    Male   
2                      Hermione Jean Granger  Female   
3    Albus Percival Wulfric Brian Dumbledore    Male   
4                         Neville Longbottom    Male   
..                                       ...     ...   
103                          Fenrir Greyback    Male   
104                      Gellert Grindelwald    Male   
105                                    Dobby    Male   
106                                 Kreacher    Male   
107                            Rubeus Hagrid    Male   

                                                   Job       House  \
0                                              Student  Gryffindor   
1                                              Student  Gryffindor   
2                                              Student  Gryffindor   
3                                           Headmaster  Gryffindor   
4                                              Student  Gryffindor   
..                                                 ...         ...   
103                                                NaN         NaN   
104           Revolutionary leader(c. 1920s[6]  1945)         NaN   
105  Malfoy family's house-elf (? - 1993),\nHogwart...         NaN   
106  \nBlack family's house-elf (?-1996), \nHarry P...         NaN   
107  Keeper of Keys and Grounds | Professor of Care...  Gryffindor   

                 Patronus                Species              Blood status  \
0                    Stag                  Human                Half-blood   
1    Jack Russell terrier                  Human                Pure-blood   
2                   Otter                  Human               Muggle-born   
3                 Phoenix                  Human                Half-blood   
4           Non-corporeal                  Human                Pure-blood   
..                    ...                    ...                       ...   
103                  None               Werewolf                       NaN   
104                   NaN                 Human   Pure-blood or half-blood   
105                   NaN              House elf                       NaN   
106                   NaN              House elf                       NaN   
107                  None  Half-Human/Half-Giant   Part-Human (Half-giant)   

                                    Wand               Hair color  \
0            11"  Holly  phoenix feather                    Black   
1             12" Ash unicorn tail hair                       Red   
2     10¾"  vine wood dragon heartstring                    Brown   
3      15" Elder Thestral tail hair core  Silver| formerly auburn   
4                13" Cherry unicorn hair                    Blond   
..                                   ...                      ...   
103                              Unknown                     Grey   
104  15", Elder, Thestral tail hair core                    Blond   
105                                  NaN                    Green   
106                                  NaN                    White   
107                 16" Oak unknown core                    Black   

        Eye color  
0    Bright green  
1            Blue  
2           Brown  
3            Blue  
4             NaN  
..            ...  
103           NaN  
104          Blue  
105           NaN  
106           NaN  
107         Black  

[108 rows x 10 columns]

### Perform DataFrame Operation for New Column

Let's setup a new DataFrame called `hp_characters_new` that contains information about some of our favorite characters.

In [111]:
# data for new dataframe
data = {'Name': ['Harry Potter', 'Ron Weasley', 'Hermione Granger', 'Ginny Weasley', 'Rubeus Hagrid','Neville Longbottom'], 
            'Job': ['Student', 'Student','Student','Student','Keeper of Keys and Grounds','Student'],
            'House': ['Gryffindor','Gryffindor','Gryffindor','Gryffindor','Gryffindor','Gryffindor'],
            'Birth Year': [1980,1980,1979,1980,1928,1980]}

# create new dataframe with the above data
hp_characters_new = pd.DataFrame(data)
hp_characters_new

Name                         Job       House  Birth Year
0        Harry Potter                     Student  Gryffindor        1980
1         Ron Weasley                     Student  Gryffindor        1980
2    Hermione Granger                     Student  Gryffindor        1979
3       Ginny Weasley                     Student  Gryffindor        1980
4       Rubeus Hagrid  Keeper of Keys and Grounds  Gryffindor        1928
5  Neville Longbottom                     Student  Gryffindor        1980

**Bonus Exercise:** Add a new column called `Age` that tells how old each character would be if they were 'alive' today.

In [123]:
import datetime
current_year = datetime.datetime.now().year

current_age = []

for i in hp_characters_new['Birth Year']:
    current_age.append(current_year - i)

In [124]:
current_age

[42, 42, 43, 42, 94, 42]

In [125]:
hp_characters_new['age'] = current_age
hp_characters_new

Name                         Job       House  Birth Year  age
0        Harry Potter                     Student  Gryffindor        1980   42
1         Ron Weasley                     Student  Gryffindor        1980   42
2    Hermione Granger                     Student  Gryffindor        1979   43
3       Ginny Weasley                     Student  Gryffindor        1980   42
4       Rubeus Hagrid  Keeper of Keys and Grounds  Gryffindor        1928   94
5  Neville Longbottom                     Student  Gryffindor        1980   42

### Other Questions

For further practice with data analysis, here are some additional questions to try to answer on your own.

- How many of the characters are female are there in the `hp_characters` DataFrame? How many of the characters are male?
- How many characters are there of each respective house?
- What are the various species represented in the dataset?
- List the various value counts for blood status.
- What job is the most represented in the data?